import fs from "fs";

// Create 200 distinct topic entries covering every single question exactly
const raw200Questions = [
  // ── 1. Voice Telephony & IVR (1-20) ──
  { q: "How does your AI voice agent handle caller accents in India?", id: "v1", ans: "Our AI Voice Agents feature acoustic model adaptation fine-tuned on diverse Indian regional accents (North, South, East, West) and Hinglish dialects to ensure high speech recognition accuracy. The speech engine filters background noise and recognizes regional speech nuances without dropping call context." },
  { q: "Can AI voice agents operate on toll-free 1800 numbers?", id: "v2", ans: "Yes! Our AI Voice Agents connect seamlessly to 1800 toll-free numbers via SIP trunking and cloud telephony gateways (Twilio, Exotel, Tata Tele) with zero line congestion. They handle high-volume inbound customer queries 24/7 on toll-free lines with automated CRM logging." },
  { q: "What is the SIP trunk integration process for voice bots?", id: "v3", ans: "SIP trunk integration connects directly via WebSockets and WebRTC to your PBX or cloud telephony provider, enabling instant call initiation and bi-directional audio streaming. Our architecture plugs into existing PBX, Asterisk, Twilio, or Exotel infrastructure without requiring any hardware changes." },
  { q: "How many simultaneous phone calls can one voice agent handle?", id: "v4", ans: "A single ConverseAI deployment can handle thousands of simultaneous concurrent phone calls automatically with auto-scaling worker queues and zero hold times. Dynamic load balancing ensures every caller gets instant response times even during peak holiday sales spikes." },
  { q: "Does the voice bot support call recording for compliance?", id: "v5", ans: "Yes! Our voice system supports automated encrypted call recording, real-time audio transcription, PII masking, and SOC2/HIPAA compliant storage in your cloud. All audio recordings and transcript summaries are indexed and securely attached to CRM contact records." },
  { q: "Can the voice agent transfer a call to a human manager?", id: "v6", ans: "Yes! Our AI Voice Agents support intelligent warm transfers to human managers or department queues when high-value leads or complex support cases require human intervention. The agent passes full caller context, audio transcripts, and sentiment metrics to the receiving manager before connecting the live line." },
  { q: "What happens when a caller speaks both Hindi and English in one sentence?", id: "v7", ans: "Our speech recognition engine is specially trained for code-switching, seamlessly understanding mixed Hindi and English (Hinglish) spoken naturally within the exact same sentence! Whether callers switch between Hindi and English phrases mid-sentence, the AI maintains full contextual understanding and responds fluently." },
  { q: "Can voice agents make automated outbound debt collection calls?", id: "v8", ans: "Yes! Our AI Voice Agents conduct automated outbound debt collection and payment reminder calls with empathetic dialogue, payment link SMS dispatch, and instant CRM logging. The agent negotiates payment dates, sends instant UPI or Razorpay payment links during the call, and respects compliance calling hours." },
  { q: "Is there any latency delay when the voice agent answers a question?", id: "v9", ans: "Our speech-to-speech voice pipeline achieves an ultra-low response latency of under 500 milliseconds using streaming Faster-Whisper VAD and optimized local LLM inference. This sub-second response speed makes conversations feel completely natural and human-like without uncomfortable awkward pauses." },
  { q: "Does your telephony system support Twilio and Exotel integration?", id: "v10", ans: "Yes! ConverseAI natively integrates with Twilio, Exotel, Tata Tele, Knowlarity, and Plivo cloud telephony providers via WebSockets and REST webhooks. You can keep your existing phone numbers and telephony providers while routing audio streams to our AI voice server." },
  { q: "How does the voice bot recognize background noise vs human voice?", id: "v11", ans: "Our voice system utilizes Silero VAD (Voice Activity Detection) paired with Web Audio bandpass filters to isolate human vocal frequencies from street traffic, office chatter, and wind noise. It ensures the AI only processes true speech, preventing background noise from triggering false responses or interrupting call flow." },
  { q: "Can we customize the voice agent tone and gender?", id: "v12", ans: "Yes! You can fully customize the voice agent's gender, accent, tone (warm, professional, empathetic, or authoritative), and speaking rate using CosyVoice2 synthetic voice cloning. We can even clone a custom corporate voice actor to maintain consistent brand identity across all customer phone calls." },
  { q: "What is the cost per minute for AI voice calls?", id: "v13", ans: "AI voice call pricing typically ranges between 3 to 6 cents ($0.03-$0.06) per minute, delivering up to 70% cost savings compared to traditional human call center seats. Self-hosted deployments eliminate per-minute SaaS markups by running directly on your cloud infrastructure." },
  { q: "Does the AI agent send SMS follow-ups after a call ends?", id: "v14", ans: "Yes! Immediately after a voice call ends, the AI agent can trigger automated SMS or WhatsApp follow-up messages containing booking confirmations, payment links, or call summary notes. This ensures callers receive written confirmation of everything discussed during the phone conversation." },
  { q: "Can voice agents book clinic appointments automatically?", id: "v15", ans: "Yes! Our AI Voice Agents handle 24/7 inbound clinic phone calls, checking doctor schedule availability, booking appointment slots, and sending SMS reminders. For healthcare providers like CareFirst Clinics, automated appointment booking slashed no-shows by 55% and saved 120 admin hours monthly." },
  { q: "How does Silero VAD detect caller speech activity?", id: "v16", ans: "Silero VAD is an advanced neural network model running locally in our voice server to analyze audio chunks in 30ms windows, detecting exact speech start and stop boundaries. It enables instant interruption detection (barge-in) and prevents silence or breathing sounds from being misprocessed as user input." },
  { q: "Does the voice agent handle missed call campaigns?", id: "v17", ans: "Yes! When a customer drops a missed call, our AI voice system instantly initiates an outbound callback within 5 seconds to engage the lead while intent is highest. This eliminates lost sales opportunities from unanswered calls during off-hours or peak phone traffic." },
  { q: "Can voice agents conduct customer satisfaction CSAT surveys?", id: "v18", ans: "Yes! Our voice agents can conduct 30-second post-resolution CSAT surveys, gathering numeric ratings and verbal customer feedback with 100% transcript sentiment analysis. Survey scores and voice transcripts are automatically mapped into your CRM reports and dashboard analytics." },
  { q: "What is the maximum duration for a single voice call?", id: "v19", ans: "By default, single voice calls are configured with a 30-minute safety limit, but this can be customized or extended based on your enterprise policy. If a caller requires extensive assistance, the agent handles the interaction smoothly or offers a warm transfer to a specialist." },
  { q: "How does the voice agent handle heavy IVR call volume spikes?", id: "v20", ans: "During sudden traffic surges (such as flash sales or service outages), our cloud auto-scaling infrastructure spins up worker instances dynamically to handle 10x call spikes with zero busy signals. Every caller receives immediate attention without waiting in long hold queues." },

  // ── 2. WhatsApp Automation & Commerce (21-40) ──
  { q: "Can WhatsApp bots send automated payment links to customers?", id: "w1", ans: "Yes! ConverseAI WhatsApp bots integrate with Razorpay, Stripe, and UPI gateways to send one-click automated payment links directly inside WhatsApp chat windows. Customers can complete transactions instantly without leaving the messaging application." },
  { q: "What is the open rate for WhatsApp broadcast marketing campaigns?", id: "w2", ans: "WhatsApp broadcast marketing campaigns consistently achieve 90%+ open rates and 35%+ click-through rates, vastly outperforming email marketing. High engagement leads to faster conversions and direct customer dialogues for promotional offers and product launches." },
  { q: "How do click-to-WhatsApp Facebook ads capture qualified leads?", id: "w3", ans: "Click-to-WhatsApp Meta & Instagram ads direct ad clickers straight into a live WhatsApp chat conversation with our AI lead qualification bot. This eliminates high website bounce rates and captures verified customer phone numbers instantly upon first interaction." },
  { q: "Can customers complete checkout directly inside WhatsApp?", id: "w4", ans: "Yes! Customers can browse multi-product catalogs, select items, enter delivery addresses, and complete checkout without ever opening an external browser window. Native WhatsApp Flows create a frictionless e-commerce shopping experience directly inside the chat." },
  { q: "Does the WhatsApp bot integrate with Shopify store catalogs?", id: "w5", ans: "ConverseAI features native real-time synchronization with Shopify, WooCommerce, Magento, and custom ERP product catalogs. Item availability, pricing updates, image galleries, and inventory levels are updated automatically across chat conversations." },
  { q: "How does abandoned cart recovery work on WhatsApp?", id: "w6", ans: "Our automated WhatsApp abandoned cart bot triggers personalized reminder messages 15 minutes after cart abandonment with dynamic discount codes. For clients like StyleMart India, this recovered lost cart sales with a 38% conversion rate and 3x repeat revenue." },
  { q: "Can WhatsApp bots handle multi-product list messages?", id: "w7", ans: "Yes! WhatsApp bots can send interactive Multi-Product List messages displaying up to 30 catalog items organized by categories with thumbnail images and prices. Customers can add items to a shopping cart with single-tap button clicks." },
  { q: "Is official WhatsApp Business API approval included in the service?", id: "w8", ans: "Yes! Our team manages 100% of the Meta Cloud API onboarding, phone number verification, and Green Tick official badge application process for your brand. We ensure full compliance with Meta Commerce policies to secure official API access quickly." },
  { q: "How many broadcast messages can we send per day on WhatsApp?", id: "w9", ans: "Meta provides tiered broadcast messaging limits starting at 1,000 unique users per day, scaling quickly to 10,000, 100,000, and unlimited daily messaging tiers as quality ratings remain high. Our compliance management keeps your account in Tier 1 health to ensure maximum throughput." },
  { q: "Can WhatsApp chatbots handle customer return requests?", id: "w10", ans: "Yes! The WhatsApp bot guides customers through self-service return and exchange requests by capturing product photos, validating order IDs, and generating reverse pickup shipping labels automatically. This automates 80% of routine return support queries without human agent workload." },
  { q: "Does the WhatsApp bot support interactive buttons and quick replies?", id: "w11", ans: "Yes! Our WhatsApp chatbots use Meta interactive CTA buttons, Quick Reply chips, and dropdown menus to guide customer choices effortlessly without typing. Button-driven flows increase user response speed and prevent spelling errors during lead qualification." },
  { q: "How does human agent handoff work inside the WhatsApp chat window?", id: "w12", ans: "When a customer requests human support or asks a complex question, the bot seamlessly transfers the conversation to a shared multi-agent inbox (Zendesk, Freshchat, or ConverseAI Inbox). Human agents view complete conversation history and AI sentiment tags before taking over the chat." },
  { q: "Can WhatsApp bots send PDF invoices and receipt attachments?", id: "w13", ans: "Yes! WhatsApp bots can dynamically generate and send PDF tax invoices, warranty cards, receipt documents, audio notes, and video guides directly to customers. Documents are generated on-the-fly from CRM/ERP transaction data and sent instantly upon order completion." },
  { q: "Is customer chat history saved in our CRM from WhatsApp?", id: "w14", ans: "Yes! 100% of WhatsApp conversation history, user preferences, lead scores, and transaction transcripts are synchronized automatically to contact records in Salesforce, HubSpot, or Zoho. Your sales and support representatives have full visibility into every past bot interaction." },
  { q: "Can WhatsApp bots send automated order tracking updates?", id: "w15", ans: "Yes! Integrated with shipping carriers (Delhivery, Shiprocket, BlueDart, FedEx), the bot automatically sends proactive WhatsApp status updates when orders are shipped, out for delivery, or delivered. Proactive notifications cut 'Where is my order?' support tickets by up to 75%." },
  { q: "How does WhatsApp chatbot pricing compare to email marketing?", id: "w16", ans: "While email marketing is cheap, it suffers from low 15% open rates. WhatsApp messaging delivers 90%+ open rates and 5x higher revenue conversions, yielding a significantly higher net ROI. Meta charges per-conversation fees (marketing vs utility categories), making targeted high-intent campaigns highly profitable." },
  { q: "Can WhatsApp bots qualify B2B SaaS leads automatically?", id: "w17", ans: "Yes! WhatsApp bots ask targeted B2B qualification questions (company size, budget, timeline, software stack) to score intent before routing qualified leads to sales AEs. Unqualified leads receive automated resource links, saving sales team bandwidth for high-value prospects." },
  { q: "Does the bot support multi-language WhatsApp conversations?", id: "w18", ans: "Yes! Our WhatsApp bot detects customer language preferences automatically (English, Hindi, Tamil, Telugu, Marathi, Gujarati, Spanish, Arabic) and responds in their native language. Language switching happens dynamically without disrupting conversation context or lead flow." },
  { q: "How does the bot prevent spam blocks on WhatsApp Business API?", id: "w19", ans: "We prevent spam blocks by enforcing strict opt-in consent verification, message frequency capping, template categorization compliance, and automated unsubscribe management. Maintaining high customer quality ratings protects your Meta Business API account from restrictions." },
  { q: "Can WhatsApp bots trigger automated feedback requests after delivery?", id: "w20", ans: "Yes! 2 hours after package delivery, the bot triggers a 1-tap CSAT rating or Google Review request via WhatsApp. Positive ratings trigger automated Google Review links, while negative feedback instantly alerts customer service managers." },

  // ── 3. Back-Office Agentic Automation (41-60) ──
  { q: "How does agentic process automation process PDF invoices?", id: "a1", ans: "Agentic Process Automation uses multi-modal vision AI to parse unstructured PDF invoices, extract line items, cross-check 3-way PO matching, validate vendor tax IDs, and log entries directly into SAP or Tally with 99.4% extraction accuracy." },
  { q: "What is an Agentic 4-week sprint delivery process?", id: "a2", ans: "Our fixed-fee 4-week Agentic Sprint follows: Week 1 Process Audit & Workflow Mapping, Week 2 Custom AI Agent Build & Model Tuning, Week 3 ERP/CRM Integration & Security Controls, Week 4 Live Production Deployment with full employee training." },
  { q: "Can AI agents handle accounts payable reconciliation automatically?", id: "a3", ans: "Yes! AI agents cross-reference incoming vendor bills against bank statements, purchase orders, and receiving slips, identifying discrepancies and flagging duplicate invoices automatically before queuing approved payments." },
  { q: "How does vendor onboarding work with agentic workflows?", id: "a4", ans: "Agentic workflows automate vendor registration by collecting tax certificates, banking details, and compliance documents via smart web portals, running automated background checks and updating ERP vendor master records." },
  { q: "Can AI agents triage IT support tickets automatically?", id: "a5", ans: "Yes! AI agents read incoming IT tickets in ServiceNow or Jira, classify incident severity, resolve common password/access issues autonomously, and assign high-priority infrastructure tickets to on-call engineers." },
  { q: "How do agentic systems integrate with legacy SAP ERP systems?", id: "a6", ans: "Agentic systems connect to SAP ECC, S/4HANA, and legacy ERPs using secure REST/SOAP APIs, RFC connectors, or headless RPA UI automation, enabling seamless read/write data operations without modifying legacy core code." },
  { q: "Can AI agents read unstructured contract documents?", id: "a7", ans: "Yes! Multi-modal LLM agents analyze complex multi-page legal contracts, identifying renewal dates, liability caps, termination clauses, and non-standard terms, outputting structured JSON summaries into your legal CRM." },
  { q: "What is the error rate for automated financial reconciliation?", id: "a8", ans: "ConverseAI financial reconciliation agents achieve an error rate of under 0.1%. Any edge-case discrepancy exceeding confidence thresholds is automatically routed to human finance controllers for 1-click review." },
  { q: "Does agentic automation require human approval before payments?", id: "a9", ans: "Yes! We implement Human-in-the-Loop (HITL) approval gates for high-value financial transactions. AI agents prepare the complete reconciliation dossier, requiring explicit digital sign-off from authorized managers before funds transfer." },
  { q: "How much back-office operational cost can agentic bots save?", id: "a10", ans: "Clients typically achieve a 60% to 80% reduction in back-office processing costs, eliminating manual data entry delays and accelerating invoice-to-pay cycles from days to minutes." },
  { q: "Can AI agents automate monthly payroll processing?", id: "a11", ans: "Yes! AI agents reconcile monthly timesheets, calculate attendance deductions, process tax withholdings, generate pay slips, and format bulk bank disbursement files with full audit trail logging." },
  { q: "How do agentic bots handle exceptions in invoice workflows?", id: "a12", ans: "When an exception occurs (e.g. price mismatch or missing PO), the AI agent flags the specific line item, notifies the responsible procurement officer via Slack/Teams with context, and holds that invoice until approved." },
  { q: "Can AI agents extract data from scanned physical documents?", id: "a13", ans: "Yes! Our OCR vision engine converts low-resolution scanned paper documents, physical receipts, and handwritten bills into clean digital data, correcting skewed scans and field alignment automatically." },
  { q: "What software tools can agentic bots interact with?", id: "a14", ans: "Agentic bots interact with enterprise software including SAP, Oracle, NetSuite, Tally, QuickBooks, Salesforce, HubSpot, Excel, Google Sheets, Gmail, Slack, Jira, and custom Web APIs." },
  { q: "Does agentic process automation replace traditional RPA tools?", id: "a15", ans: "Agentic AI enhances traditional RPA by adding cognitive reasoning and LLM document understanding. Unlike rigid RPA scripts that break when UI layouts change, agentic bots adapt dynamically to varying document formats." },
  { q: "How fast can an agentic invoice bot be deployed live?", id: "a16", ans: "A production-ready invoice processing bot is deployed live in just 4 weeks under our fixed-fee sprint model, with working prototypes delivered within the first 10 days." },
  { q: "Can agentic bots generate daily financial summary reports?", id: "a17", ans: "Yes! AI bots aggregate daily cash flow, open accounts receivable, pending vendor bills, and sales receipts across multiple bank accounts and ERPs, emailing executive PDF summaries every morning at 8 AM." },
  { q: "How does security control user access in agentic workflows?", id: "a18", ans: "Agentic workflows enforce strict Role-Based Access Control (RBAC), OAuth 2.0 authentication, encrypted secret vault storage, and granular audit logs for every API call and document read operation." },
  { q: "Can agentic bots execute multi-step cross-platform tasks?", id: "a19", ans: "Yes! Agentic bots execute multi-step workflows across systems — e.g. extracting a customer PO from email, checking stock in ERP, creating a shipping order in logistics portal, and emailing the invoice." },
  { q: "What happens if an invoice has missing vendor details?", id: "a20", ans: "If vendor details are missing, the bot queries master CRM records using tax registration numbers. If still unverified, it automatically emails the vendor requesting updated W-9/GST documentation." },

  // ── 4. Custom SDR & Sales AI Outreach (61-80) ──
  { q: "How do custom SDR AI agents research prospect leads on LinkedIn?", id: "s1", ans: "SDR AI agents analyze prospect LinkedIn profiles, recent company posts, job changes, funding announcements, and technology stacks to craft hyper-personalized outreach messages specific to their pain points." },
  { q: "Can SDR agents send personalized cold emails automatically?", id: "s2", ans: "Yes! Custom SDR agents generate personalized 1-on-1 cold email campaigns, managing inbox warmup, domain reputation, automated follow-up sequences, and unsubscribe requests according to CAN-SPAM regulations." },
  { q: "How does the SDR agent score lead intent before booking a call?", id: "s3", ans: "The SDR agent evaluates lead intent using BANT criteria (Budget, Authority, Need, Timeline), engagement tracking (email opens, link clicks, website visits), and conversational responses before offering demo slots." },
  { q: "Can custom SDR agents integrate with Outreach and Salesloft?", id: "s4", ans: "Yes! SDR agents integrate natively with Outreach.io, Salesloft, Apollo.io, and HubSpot Sales Hub, automatically enrolling qualified prospects into outreach cadences and logging email replies." },
  { q: "How does the SDR agent handle prospect negative replies?", id: "s5", ans: "When a prospect replies negatively ('not interested' or 'too expensive'), the AI categorizes the objection type, logs it in CRM, and politely marks the lead as nurtured or unsubscribed without sending aggressive pushback." },
  { q: "Can SDR agents book meetings directly into Google Calendar?", id: "s6", ans: "Yes! SDR agents sync bi-directionally with Google Calendar, Outlook 365, and Calendly, presenting available real-time time slots and sending calendar invites with video call links upon prospect confirmation." },
  { q: "What lead qualification frameworks do SDR agents use?", id: "s7", ans: "SDR agents can be configured with BANT, MEDDIC, or CHAMP qualification frameworks, asking natural conversational questions to verify budget range, authority level, and project timelines." },
  { q: "Can custom SDR agents generate personalized video openers?", id: "s8", ans: "Yes! SDR agents integrate with AI video generators (HeyGen, Synthesia) to produce personalized 30-second video introductions greeting prospects by name and showcasing tailored pitch decks." },
  { q: "How many prospect leads can an SDR AI agent research per hour?", id: "s9", ans: "An SDR AI agent can thoroughly research, enrich, and personalize outreach messaging for up to 500 prospect leads per hour — equivalent to the throughput of a 20-person human SDR team." },
  { q: "Does the SDR agent check for duplicate contacts in Salesforce?", id: "s10", ans: "Yes! Before initiating outreach, the agent queries Salesforce/HubSpot to ensure the contact is not an existing customer, open opportunity, or active account assigned to a human AE." },
  { q: "Can SDR agents handle multi-touch omni-channel campaigns?", id: "s11", ans: "Yes! SDR agents orchestrate multi-touch campaigns across Email, LinkedIn InMail, WhatsApp, and automated Phone Calls, maintaining unified conversation context across all communication channels." },
  { q: "How does the SDR agent craft personalized value propositions?", id: "s12", ans: "The SDR agent cross-references company industry, employee headcounts, and recent news against your case studies, selecting the exact ROI metrics (e.g. 3x revenue or 55% no-show drop) relevant to that prospect." },
  { q: "Can SDR agents research company news and funding rounds?", id: "s13", ans: "Yes! SDR agents ingest real-time news APIs, Crunchbase funding alerts, and SEC filings to trigger timely outreach when a target company raises capital or expands leadership." },
  { q: "What is the average reply rate for AI SDR outreach?", id: "s14", ans: "Hyper-personalized AI SDR outreach typically achieves 8% to 14% positive reply rates — 3x higher than generic mass cold email templates." },
  { q: "Can we customize the tone and persona of our SDR AI agent?", id: "s15", ans: "Yes! You can tailor the SDR agent's tone — from consultative enterprise advisor to energetic startup founder — aligning vocabulary and messaging style with your brand guidelines." },
  { q: "Does the SDR agent hand off hot leads to human AEs?", id: "s16", ans: "Yes! As soon as a prospect demonstrates high intent or agrees to a meeting, the agent assigns the contact to the designated human AE, attaching complete research briefs and transcript history." },
  { q: "How does the SDR agent avoid spam filter triggers on email?", id: "s17", ans: "SDR agents enforce SPF/DKIM/DMARC authentication, dynamic sending volume throttle limits, variable phrasing syntax, and spam keyword avoidance to ensure 98%+ primary inbox deliverability." },
  { q: "Can SDR agents draft tailored RFP response proposals?", id: "s18", ans: "Yes! SDR agents parse incoming RFP specification PDFs, search your corporate Knowledge Intelligence repository for compliant answers, and draft complete proposal responses for sales team review." },
  { q: "What data sources does the SDR agent use for lead enrichment?", id: "s19", ans: "SDR agents enrich lead records using data providers including Apollo, ZoomInfo, Clearbit, LinkedIn Sales Navigator, Crunchbase, and GitHub repositories." },
  { q: "How long does it take to train a custom SDR AI agent?", id: "s20", ans: "A custom SDR AI agent is fully trained on your ICP (Ideal Customer Profile), case studies, and brand voice within 2 weeks, launching live campaigns by Week 3." },

  // ── 5. Document & Knowledge Intelligence (81-100) ──
  { q: "How does private document AI read internal company SOPs?", id: "k1", ans: "Document AI chunks internal company SOP PDFs/DOCX files, converts them into high-dimensional vector embeddings using all-MiniLM-L6-v2, and indexes them in a private vector database for instant citation-backed RAG search." },
  { q: "Can Knowledge Intelligence search legal contracts for specific clauses?", id: "k2", ans: "Yes! Knowledge Intelligence searches legal repositories to instantly surface specific indemnification, termination, IP rights, or liability cap clauses with exact section number citations." },
  { q: "Does the AI provide exact page citations for its answers?", id: "k3", ans: "Yes! Every answer generated by Knowledge Intelligence includes exact document source titles, page numbers, and snippet quotes so employees can verify information instantly." },
  { q: "Can Knowledge Intelligence be hosted on private AWS servers?", id: "k4", ans: "Yes! Knowledge Intelligence can be deployed 100% on-premise or within your private AWS, Azure, or Google Cloud VPC, ensuring no document data ever touches external public LLM servers." },
  { q: "How does permission-aware AI restrict confidential HR data?", id: "k5", ans: "Permission-aware RAG integrates with Active Directory/Okta RBAC, ensuring employees only receive search results and answers from documents their role is authorized to view." },
  { q: "Can the document AI parse 500-page technical PDF manuals?", id: "k6", ans: "Yes! Our ingestion pipeline parses 500+ page technical manuals, extracting text, diagrams, tables, and nested chapter hierarchies with sub-second vector search performance." },
  { q: "How fast does Knowledge Intelligence return answers from documents?", id: "k7", ans: "Semantic vector search returns citation-backed answers in under 300 milliseconds across repositories containing tens of thousands of documents." },
  { q: "Does the AI update its vector database when SOPs change?", id: "k8", ans: "Yes! Webhook listeners auto-detect file updates in Google Drive, Notion, or SharePoint, automatically re-indexing vector embeddings so answers always reflect the latest policy revisions." },
  { q: "Can Knowledge Intelligence answer employee onboarding queries?", id: "k9", ans: "Yes! Internal HR AI bots answer new hire questions regarding benefits, leave policies, IT setup, and company guidelines 24/7, reducing HR admin tickets by 70%." },
  { q: "Is client contract data kept 100% private in isolated clouds?", id: "k10", ans: "Yes! All client documents, embeddings, and chat histories are isolated in single-tenant data stores with AES-256 encryption at rest and TLS 1.3 in transit." },
  { q: "Can Knowledge Intelligence integrate with Notion and Confluence?", id: "k11", ans: "Yes! We support native API connectors for Notion, Confluence, SharePoint, Google Drive, Dropbox, Box, and Jira Knowledge Bases." },
  { q: "How does the vector RAG engine prevent AI hallucinations?", id: "k12", ans: "The RAG engine enforces strict prompt grounding rules — forcing the LLM to answer exclusively using retrieved vector context snippets. If context is missing, it explicitly states information is unverified." },
  { q: "Can Document AI compare two version revisions of a contract?", id: "k13", ans: "Yes! Document AI compares multi-page contract revisions side-by-side, highlighting added, deleted, or modified legal clauses and assessing risk level changes." },
  { q: "What document formats are supported by Knowledge Intelligence?", id: "k14", ans: "We support PDF, DOCX, TXT, CSV, XLSX, PPTX, HTML, Markdown, scanned images (via OCR), and web URLs." },
  { q: "Does Knowledge Intelligence support multi-lingual document translation?", id: "k15", ans: "Yes! Employees can upload a document in German or Hindi and ask questions in English (or vice versa), receiving accurate citation-backed answers in their preferred language." },
  { q: "How does Superadmin re-index knowledge after website updates?", id: "k16", ans: "Superadmins can trigger an immediate full re-index via the protected `/api/reindex` endpoint or Admin Dashboard button, re-crawling sitemaps and regenerating vector embeddings in minutes." },
  { q: "Can Document AI extract structured JSON tables from PDFs?", id: "k17", ans: "Yes! Vision-LLM models parse complex multi-column PDF tables, financial balance sheets, and invoice line items, outputting clean structured JSON schemas." },
  { q: "Is there a file size limit for internal SOP uploads?", id: "k18", ans: "Standard file upload limit is 100MB per file, but larger technical manuals up to 1GB can be processed via stream chunking." },
  { q: "How does Knowledge Intelligence enforce tenant data isolation?", id: "k19", ans: "Multi-tenant deployments isolate data using separate vector database namespaces and tenant ID query filters, ensuring zero cross-tenant data leakage." },
  { q: "Can employees chat with company knowledge bases via Slack?", id: "k20", ans: "Yes! We build custom Slack and Microsoft Teams bots that allow employees to tag `@KnowledgeBot` in channels to receive instant citation-backed answers from company SOPs." },

  // ── 6. CRM & Software Integrations (101-120) ──
  { q: "How does ConverseAI integrate with Salesforce CRM?", id: "c1", ans: "We integrate via Salesforce REST API & Apex Webhooks — creating Lead/Contact records, updating Opportunity stages, logging call audio transcripts, and triggering Salesforce Flows in real time." },
  { q: "Can AI agents update contact deal stages in HubSpot automatically?", id: "c2", ans: "Yes! AI agents call HubSpot CRM APIs to advance pipeline deal stages, add engagement timeline notes, assign tasks to owners, and update custom contact properties automatically." },
  { q: "Does ConverseAI support Zoho CRM and LeadSquared integration?", id: "c3", ans: "Yes! We provide full native integration support for Zoho CRM, LeadSquared, Freshsales, and Pipedrive, ensuring multi-channel lead data syncs seamlessly." },
  { q: "How do AI agents connect with Zendesk for support tickets?", id: "c4", ans: "AI agents interface with Zendesk Support API — creating tickets, updating status, adding internal comments, and resolving routine inquiries automatically." },
  { q: "Can AI agents sync data with internal REST API webhooks?", id: "c5", ans: "Yes! Custom webhooks allow AI agents to send and receive real-time JSON payloads to any internal REST/GraphQL API or microservice." },
  { q: "Is Tally accounting software integration supported?", id: "c6", ans: "Yes! We integrate with Tally Prime and Tally.ERP 9 via Tally XML API / ODBC connectors, automating sales voucher entry, receipt posting, and ledger reconciliation." },
  { q: "How does real-time bi-directional CRM sync work?", id: "c7", ans: "Bi-directional sync listens for webhooks from your CRM (e.g. status change) while pushed agent updates write back immediately, maintaining 100% data consistency." },
  { q: "Can AI agents log call audio recordings into HubSpot contacts?", id: "c8", ans: "Yes! Upon call completion, the AI agent uploads encrypted audio MP3 recordings, text transcripts, and AI key points directly to the corresponding HubSpot contact timeline." },
  { q: "What authentication protocols are used for API integrations?", id: "c9", ans: "We enforce enterprise security protocols including OAuth 2.0, mTLS, HMAC SHA-256 signature verification, and encrypted API key vaults." },
  { q: "Does ConverseAI require replacing existing enterprise software?", id: "c10", ans: "No! ConverseAI solutions overlay on top of your existing software stack (CRMs, ERPs, Telephony), enhancing workflows without requiring expensive rip-and-replace software migrations." },
  { q: "Can AI agents trigger automated Zapier or Make workflows?", id: "c11", ans: "Yes! AI agents trigger Zapier webhooks or Make.com scenarios to connect with over 5,000+ third-party cloud applications." },
  { q: "How does ConverseAI handle CRM API rate limits?", id: "c12", ans: "Our middleware implements exponential backoff retries, request throttling queues, and batch payload processing to remain strictly within CRM API quota limits." },
  { q: "Can AI agents create new leads in Pipedrive automatically?", id: "c13", ans: "Yes! When a new prospect engages on WhatsApp or Voice, the agent extracts contact details, qualifies buyer intent, and creates a formatted Lead in Pipedrive instantly." },
  { q: "Is ServiceNow integration available for enterprise IT?", id: "c14", ans: "Yes! We integrate with ServiceNow IT Service Management (ITSM), automating incident creation, CMDB configuration lookup, and user access provisioning." },
  { q: "How fast can a custom CRM API integration be built?", id: "c15", ans: "Custom REST API connectors are built and verified within 3 to 5 business days using our modular SDK integration framework." },
  { q: "Does ConverseAI provide custom webhook endpoints for callbacks?", id: "c16", ans: "Yes! Every client deployment receives dedicated HTTPS webhook endpoints with signature validation for real-time event callbacks." },
  { q: "Can AI agents update inventory status in SAP ERP?", id: "c17", ans: "Yes! AI agents connect to SAP via BAPI/OData services, checking stock availability and updating inventory line items in real time as orders are confirmed." },
  { q: "How are integration errors logged and retried?", id: "c18", ans: "Failed API requests are logged in administrative audit trails with automatic dead-letter queue retries and instant alert notifications via Slack/email." },
  { q: "Can AI agents read custom fields from Salesforce objects?", id: "c19", ans: "Yes! Our dynamic schema mapper reads standard and custom fields (`__c`) from Salesforce Lead, Contact, Account, and Opportunity objects." },
  { q: "Is multi-CRM sync supported for enterprise holding companies?", id: "c20", ans: "Yes! Multi-tenant routing rules allow AI agents to sync leads and support cases to different CRMs based on subsidiary brand or geographic region." },

  // ── 7. Enterprise Security & Compliance (121-140) ──
  { q: "Is ConverseAI fully SOC2 Type II compliant?", id: "se1", ans: "Yes! ConverseAI solution architectures are fully SOC2 Type II compliant and HIPAA ready, featuring stringent access controls, vulnerability scanning, and audit logging." },
  { q: "How does ConverseAI satisfy HIPAA compliance requirements?", id: "se2", ans: "We satisfy HIPAA compliance through business associate agreements (BAAs), PII/PHI redaction algorithms, AES-256 data encryption, and dedicated single-tenant VPC deployments." },
  { q: "Who owns 100% of the custom code, data, and IP assets?", id: "se3", ans: "You do! Clients retain 100% full ownership of all custom agent source code, fine-tuned model weights, proprietary data, and intellectual property." },
  { q: "Do clients get isolated tenant cloud environments?", id: "se4", ans: "Yes! Enterprise clients receive dedicated isolated cloud VPC environments (AWS/Azure/GCP) with private networking and dedicated compute resources." },
  { q: "Is client conversation data ever sold or used for training?", id: "se5", ans: "Never. Client conversation data, transcripts, and document knowledge are 100% private and NEVER sold, shared, or used to train public LLM models." },
  { q: "What encryption standards are used for data in transit?", id: "se6", ans: "All network traffic is encrypted using TLS 1.3 / HTTPS / WSS protocols in transit, paired with AES-256 bit encryption for data at rest." },
  { q: "How does ConverseAI handle GDPR data privacy requests?", id: "se7", ans: "We support automated 'Right to be Forgotten' data deletion requests, exporting or purging user transcripts and PII records within 24 hours of request." },
  { q: "Are penetration testing reports available for enterprise clients?", id: "se8", ans: "Yes! Executive summaries of third-party annual penetration testing and vulnerability assessment reports are shared with enterprise security review teams under NDA." },
  { q: "What physical and cloud security controls protect server data?", id: "se9", ans: "Cloud infrastructure is hosted in ISO 27001 / SOC2 certified data centers with 24/7 biometric physical security, DDoS protection, and automated failover backups." },
  { q: "Can AI models be deployed on-premise inside private data centers?", id: "se10", ans: "Yes! Self-hosted models (Ollama Qwen2.5, Whisper, CosyVoice2) can be deployed 100% on-premise inside your private data center or air-gapped network." },
  { q: "Does ConverseAI sign Business Associate Agreements for healthcare?", id: "se11", ans: "Yes! We execute standard HIPAA Business Associate Agreements (BAAs) for healthcare clinics, hospital networks, and healthtech providers." },
  { q: "How are API keys and secret tokens managed securely?", id: "se12", ans: "API keys and database credentials are stored in encrypted hardware security modules (AWS Secrets Manager / HashiCorp Vault) with automated secret rotation." },
  { q: "What is the system uptime SLA for enterprise deployments?", id: "se13", ans: "Enterprise service level agreements (SLAs) guarantee 99.9% uptime with 24/7 active-active multi-region cloud redundancy." },
  { q: "How does disaster recovery failover work in cloud regions?", id: "se14", ans: "Automated multi-region failover redirects WebSocket and HTTP traffic to secondary hot-standby cloud regions within 30 seconds if a primary region degrades." },
  { q: "Are administrative actions logged in audit security trails?", id: "se15", ans: "Yes! 100% of administrative login attempts, configuration updates, data exports, and re-indexing events are recorded in immutable audit logs." },
  { q: "How does role-based access control restrict admin permissions?", id: "se16", ans: "RBAC policies restrict access based on user role — differentiating Superadmins, Content Editors, Support Agents, and Read-Only Auditors." },
  { q: "What security headers protect ConverseAI web endpoints?", id: "se17", ans: "All web endpoints enforce strict HTTP security headers including Content-Security-Policy (CSP), Strict-Transport-Security (HSTS), X-Frame-Options, and X-Content-Type-Options." },
  { q: "Can enterprise security teams conduct vulnerability scans?", id: "se18", ans: "Yes! We coordinate authorized penetration testing and automated vulnerability scans with client InfoSec teams prior to production launch." },
  { q: "How is PII data masked in voice and text transcripts?", id: "se19", ans: "Real-time regex and NER models detect credit card numbers, SSNs, and passwords in speech/text streams, redacting them to `[REDACTED]` before saving transcripts." },
  { q: "What compliance standards govern financial transaction bots?", id: "se20", ans: "Financial transaction bots comply with PCI-DSS guidelines for payment tokenization, ensuring raw credit card details are never stored on bot servers." },

  // ── 8. Pricing, Sprints & Engagement Model (141-160) ──
  { q: "How much cheaper are ConverseAI solutions compared to US agencies?", id: "p1", ans: "Powered by our core engineering hub in Jaipur, India, ConverseAI delivers US-grade AI engineering standards at 40% to 60% below US boutique agency pricing." },
  { q: "What is included in a 4-week fixed-fee Agent Sprint?", id: "p2", ans: "A 4-week Agent Sprint includes workflow auditing, custom model fine-tuning, CRM integration, security setup, QA benchmark testing, and production deployment with zero budget overruns." },
  { q: "Is the AI Strategy Audit fee credited toward the first build?", id: "p3", ans: "Yes! 100% of the 2-week AI Strategy & Readiness Audit fee is credited directly toward your first 4-week productized AI deployment." },
  { q: "Do you offer fixed-fee proposals with zero cost overruns?", id: "p4", ans: "Yes! Every project engagement is structured under a transparent fixed-fee proposal, eliminating hourly billing surprises or unexpected scope creep." },
  { q: "How long does a 3-week AI Strategy Audit engagement take?", id: "p5", ans: "The AI Strategy Audit spans 2 to 3 weeks, delivering a complete operational bottleneck evaluation, ROI calculation matrix, and technical roadmap." },
  { q: "What is the proof-of-concept prototype delivery timeline?", id: "p6", ans: "Working proof-of-concept (POC) prototypes are delivered within 7 to 10 business days for early stakeholder evaluation." },
  { q: "Are there any recurring hidden software licensing fees?", id: "p7", ans: "No! We provide transparent cost breakdowns. Self-hosted options eliminate per-seat SaaS licensing markups." },
  { q: "How does ConverseAI structure client payment milestones?", id: "p8", ans: "Standard engagement milestones are structured as: 40% Deposit upon kickoff, 40% upon POC Milestone Sign-off, and 20% upon Final Production Launch." },
  { q: "What is the cost of ongoing maintenance and agent tuning?", id: "p9", ans: "Ongoing monthly maintenance plans cover model re-tuning, API updates, performance monitoring, and SLA support at a low predictable retainer." },
  { q: "Can companies upgrade their sprint scope during development?", id: "p10", ans: "Yes! Sprints are managed agilely — scope additions can be incorporated into follow-on sprint cycles without disrupting current build timelines." },
  { q: "What ROI metrics can clients expect within 90 days?", id: "p11", ans: "Clients typically report 3x higher lead conversion rates, 65% reduction in support costs, or 120+ admin hours saved per month within 90 days." },
  { q: "Do you offer dedicated account managers for enterprise clients?", id: "p12", ans: "Yes! Enterprise clients receive a dedicated AI Solution Architect and Technical Account Manager for daily Slack/Teams communication." },
  { q: "How does fixed-fee sprint pricing prevent budget creep?", id: "p13", ans: "Fixed-fee pricing locks deliverables, architecture specs, and timelines upfront, ensuring your project is completed on budget." },
  { q: "What happens after the initial 4-week agent deployment?", id: "p14", ans: "After deployment, we provide 30 days of hyper-care support, followed by optional ongoing optimization retainer plans." },
  { q: "Can SMB startups afford ConverseAI custom AI development?", id: "p15", ans: "Yes! Our productized sprint model makes custom enterprise-grade AI accessible and affordable for growing SMB startups." },
  { q: "What is the cost comparison between AI agents and human staff?", id: "p16", ans: "An AI agent costs up to 70% less than hiring equivalent full-time human staff, operating 24/7/365 with zero turnover or training overhead." },
  { q: "Are there discounts for annual enterprise service contracts?", id: "p17", ans: "Yes! We offer 15% to 20% discounts on annual multi-sprint and maintenance retainer contracts." },
  { q: "How do we request a custom project proposal?", id: "p18", ans: "You can request a custom proposal by scheduling a 15-minute discovery call or submitting your project details on our Contact page." },
  { q: "What is the refund policy if project milestones are delayed?", id: "p19", ans: "We stand behind our milestone delivery SLAs — if a core sprint milestone is missed due to our delay, milestone fees are adjusted or credited." },
  { q: "Why choose ConverseAI over offshore contract developers?", id: "p20", ans: "Unlike freelance contractors, ConverseAI delivers productized AI systems built by senior engineers in Jaipur with full IP ownership, SOC2 security, and guaranteed SLAs." },

  // ── 9. Case Studies & Verified Results (161-180) ──
  { q: "How did StyleMart India achieve 3x repeat purchase revenue?", id: "cs1", ans: "StyleMart India deployed ConverseAI WhatsApp AI Chatbot for automated post-purchase recommendations & abandoned cart recovery, driving 3x repeat purchase revenue & 65% support cost reduction." },
  { q: "What reduction in support costs did StyleMart report on WhatsApp?", id: "cs2", ans: "StyleMart India achieved a 65% reduction in customer support operational costs by automating routine order status and return queries." },
  { q: "How did LearnSphere double student enrolments in 90 days?", id: "cs3", ans: "LearnSphere used ConverseAI interactive WhatsApp AI lead bot to qualify student inquiries in 30 seconds, doubling course enrolments in 90 days and cutting response time by 80%." },
  { q: "By how much did LearnSphere cut lead response time?", id: "cs4", ans: "LearnSphere cut lead response time by 80% — responding to prospective students within 5 seconds of ad clicks." },
  { q: "How did CareFirst Clinics cut appointment no-shows by 55%?", id: "cs5", ans: "CareFirst Clinics deployed automated WhatsApp reminder & voice call agents, reducing missed appointments by 55% across 12 clinic locations and saving 120 admin hours monthly." },
  { q: "How many admin hours per month did CareFirst Clinics save?", id: "cs6", ans: "CareFirst Clinics saved 120 administrative staff hours per month through automated appointment scheduling and patient follow-up calls." },
  { q: "What results did B2B SaaS clients achieve with sales AI?", id: "cs7", ans: "B2B SaaS clients achieved a 3.5x increase in qualified demo bookings and a 45% reduction in customer acquisition cost using Custom SDR AI outreach." },
  { q: "Where can I read full client case studies on your website?", id: "cs8", ans: "You can read complete verified client case studies with metrics and walkthroughs at `/case-studies` on our website." },
  { q: "Can ConverseAI share client references for healthcare AI?", id: "cs9", ans: "Yes! We provide verified client references and healthcare case study walkthroughs under NDA during executive discovery calls." },
  { q: "What retail fashion brands use ConverseAI WhatsApp bots?", id: "cs10", ans: "Retail fashion brands like StyleMart India utilize ConverseAI WhatsApp bots for catalog sales, order tracking, and cart recovery." },
  { q: "What edtech platforms use ConverseAI lead qualification?", id: "cs11", ans: "EdTech platforms like LearnSphere use ConverseAI to automate student lead qualification, course recommendations, and instant enrollment booking." },
  { q: "What healthcare networks use ConverseAI appointment voice bots?", id: "cs12", ans: "Multi-branch clinic networks like CareFirst Clinics use ConverseAI voice agents for 24/7 inbound patient scheduling." },
  { q: "What back-office invoice savings did financial clients see?", id: "cs13", ans: "Financial and accounting clients achieved a 75% reduction in invoice processing time and zero data entry errors." },
  { q: "How did ConverseAI help a logistics company streamline support?", id: "cs14", ans: "ConverseAI automated 80% of shipment tracking, ETA queries, and delivery rescheduling for global logistics clients via WhatsApp & Voice." },
  { q: "What CSAT score improvement did real estate clients achieve?", id: "cs15", ans: "Real estate clients improved CSAT scores from 3.8 to 4.8 out of 5 by offering instant 24/7 property inquiry responses." },
  { q: "Can I view video walkthroughs of client case studies?", id: "cs16", ans: "Yes! Interactive video walkthroughs and system architecture diagrams are available on each case study page." },
  { q: "What conversion rates do WhatsApp abandoned cart bots deliver?", id: "cs17", ans: "ConverseAI WhatsApp abandoned cart bots deliver a 38% conversion rate on recovered shopping carts." },
  { q: "How fast did StyleMart see positive ROI after launch?", id: "cs18", ans: "StyleMart India achieved full positive ROI within 30 days of deploying ConverseAI WhatsApp automation." },
  { q: "What lead volume increase did edtech clients experience?", id: "cs19", ans: "LearnSphere experienced a 2x increase in qualified student lead volume within 90 days of launch." },
  { q: "Are case study metrics verified by independent clients?", id: "cs20", ans: "Yes! All published case study metrics, revenue growth numbers, and operational savings are independently verified by client stakeholders." },

  // ── 10. Jaipur Engineering Hub & Contact (181-200) ──
  { q: "Where is ConverseAI core engineering team headquartered?", id: "j1", ans: "ConverseAI's core engineering hub is headquartered in Jaipur, Rajasthan, India, powering productized AI solutions for global clients." },
  { q: "Why is ConverseAI engineering hub located in Jaipur?", id: "j2", ans: "Our Jaipur engineering hub combines elite AI engineering talent with a cost structure that delivers US-grade solutions at 40-60% below Western agency rates." },
  { q: "How does Jaipur engineering deliver US-grade AI standards?", id: "j3", ans: "Our Jaipur team consists of senior AI architects trained in SOC2 compliance, vector RAG, voice models, and enterprise software integration." },
  { q: "Can international clients visit the Jaipur engineering office?", id: "j4", ans: "Yes! We welcome international clients to visit our Jaipur engineering headquarters for in-person strategy workshops and technical sprints." },
  { q: "What timezone does the Jaipur engineering team operate in?", id: "j5", ans: "Our Jaipur team operates on IST (Indian Standard Time) with dedicated overlapping coverage windows for US (EST/PST) and European (GMT/CET) business hours." },
  { q: "How do I schedule a 15-minute discovery call with the team?", id: "j6", ans: "You can schedule a 15-minute discovery call instantly by clicking 'Book Call' or submitting your details on our Contact Us page." },
  { q: "What time slots are available for demo calls tomorrow?", id: "j7", ans: "Discovery call slots are available daily between 9 AM and 8 PM IST (or equivalent US/EU times). Click 'Book Call' to pick your preferred slot." },
  { q: "How fast does the ConverseAI team respond to contact inquiries?", id: "j8", ans: "Our team responds to all contact inquiries within 2 business hours (and under 15 minutes during active business hours)." },
  { q: "Can I request a custom live demo for my business?", id: "j9", ans: "Yes! We provide tailored live demos showcasing AI Voice Agents or WhatsApp Chatbots customized specifically to your industry." },
  { q: "What details are needed to book a consultation session?", id: "j10", ans: "Just your name, business email or phone number, and a brief note on the AI solution you are interested in exploring." },
  { q: "Can I speak directly with an AI solution architect?", id: "j11", ans: "Yes! All discovery calls are conducted directly by a senior AI Solution Architect, not junior sales reps." },
  { q: "Where can I find ConverseAI office address and contact info?", id: "j12", ans: "You can find complete office addresses, contact numbers, and email details at `/contact-us`." },
  { q: "How do I submit a project inquiry on the Contact page?", id: "j13", ans: "Navigate to `/contact-us`, fill in the simple form fields, and click Submit — our team will reach out within 2 hours." },
  { q: "Does ConverseAI offer remote video call consultations?", id: "j14", ans: "Yes! We conduct remote video consultations via Google Meet or Zoom for clients worldwide." },
  { q: "What happens after I submit the Contact Us form?", id: "j15", ans: "An AI Solution Architect reviews your requirements, prepares initial project thoughts, and emails you to confirm a 15-minute discovery call." },
  { q: "Can I book a discovery call for AI Voice Agents specifically?", id: "j16", ans: "Yes! You can select 'AI Voice Agents' as your topic of interest when booking a discovery call." },
  { q: "Can I book a discovery call for WhatsApp AI Chatbot?", id: "j17", ans: "Yes! You can select 'WhatsApp AI Chatbot' when scheduling your consultation." },
  { q: "Can I book a discovery call for Agentic Automation?", id: "j18", ans: "Yes! Select 'Agentic Process Automation' during call booking to speak with an automation specialist." },
  { q: "Can I book a discovery call for Custom AI Agent Development?", id: "j19", ans: "Yes! Choose 'Custom AI Agents' to discuss bespoke SDR, AR, or support agent development." },
  { q: "How do I reach ConverseAI customer support directly?", id: "j20", ans: "You can reach customer support 24/7 via the Aira Voice Assistant on our website or by emailing `support@theconverseai.com`." }
];

let code = `export interface KnowledgeTopic {
  id: string;
  keywords: string[];
  title: string;
  path: string;
  benefits: string;
  details: string;
  followUp: string;
}

export const ALL_200_APPROVED_KNOWLEDGE: KnowledgeTopic[] = [
`;

for (const item of raw200Questions) {
  // Extract keywords from query
  const cleanQ = item.q.toLowerCase().replace(/[^a-z0-9\s]/g, "");
  const words = cleanQ.split(/\s+/).filter(w => w.length > 3 && !['what', 'how', 'can', 'does', 'do', 'is', 'are', 'the', 'your', 'for', 'with'].includes(w));
  const kw1 = item.q.toLowerCase().replace(/[?.]/g, "");
  const kw2 = words.slice(0, 4).join(" ");
  const kw3 = words.slice(-3).join(" ");

  code += `  {
    id: "${item.id}",
    keywords: ${JSON.stringify([kw1, kw2, kw3, ...words])},
    title: "${item.id}",
    path: "/services",
    benefits: ${JSON.stringify(item.ans)},
    details: "We build productized AI solutions shipped in weeks with zero framework lock-in.",
    followUp: "Would you like to explore how this AI solution fits your business requirements?"
  },\n`;
}

code += `];\n`;

fs.writeFileSync("src/components/VoiceAssistant/topicsData.ts", code);
console.log("✅ Successfully written 200 distinct topics into topicsData.ts!");
