import fs from "fs";

const data = JSON.parse(fs.readFileSync("scratch_200_results.json", "utf8"));

let md = "# 200 Unique Voice Agent Verification Test Results\n\n";
md += "Below is the complete 200-question verification table generated by running all 200 unique test questions through the Converse AI Voice Agent engine across 10 functional domains.\n\n";

let currentDomain = "";
for (const item of data) {
  if (item.domain !== currentDomain) {
    currentDomain = item.domain;
    md += `\n## Domain: ${currentDomain}\n\n`;
    md += "| # | User Question | Voice Agent Answer |\n";
    md += "|---|---|---|\n";
  }
  const q = item.question.replace(/\|/g, "\\|");
  const a = item.answer.replace(/\|/g, "\\|").replace(/\n/g, " ");
  md += `| **${item.id}** | ${q} | ${a} |\n`;
}

fs.writeFileSync(
  "C:/Users/JANVI/.gemini/antigravity/brain/69132b7a-8358-4604-9b66-59ebca26e5bc/200_verification_questions.md",
  md
);
console.log("Markdown table file created successfully!");
